import type { ToolGuideProps } from '@/components/ToolGuide';
import type { FAQItem } from '@/components/FAQ';

export type ToolContentData = {
  guide: ToolGuideProps;
  faqs: FAQItem[];
};

export const TOOL_CONTENT: Record<string, ToolContentData> = {
  'photo-resizer': {
    guide: {
      title: 'What is the Image Resizer Tool?',
      overview: 'The KagazKit Image Resizer is a specialized utility designed to resize and compress photographs to meet the strict dimensional and file size requirements demanded by Indian government exam portals and official document submissions. Government portals for UPSC, SSC, IBPS, Railway, and other competitive exams require photos in very specific pixel dimensions (e.g., 200×230 or 350×350 pixels) and strict file size ranges (typically 20KB to 50KB). Manually achieving this with generic photo editors is frustrating and error-prone. Our tool automates the entire process with a smart binary-search compression algorithm that finds the perfect JPEG quality level to hit your target KB range.',
      steps: [
        { step: 'Select a preset format', description: 'Choose from UPSC, SSC, IBPS presets or set custom dimensions and KB limits for your specific portal.' },
        { step: 'Upload your photo', description: 'Click the upload area or drag-and-drop your passport-size photo. Supports JPG, PNG, and WebP formats up to 10MB.' },
        { step: 'Click "Resize & Compress"', description: 'The tool resizes your image to the exact pixel dimensions and uses an iterative compression algorithm to fit within the target KB range.' },
        { step: 'Download the result', description: 'Review the final file size shown on screen, then click "Download Image" to save the compliant file to your device.' },
      ],
      features: [
        '100% client-side — your photo never leaves your device',
        'Binary-search compression for pixel-perfect KB targeting',
        'Pre-built presets for UPSC, SSC CGL, IBPS PO exams',
        'Custom dimensions and KB limits for any portal',
        'Supports JPG, PNG, and WebP input formats',
        'Instant processing with no server upload wait times',
      ],
      useCases: [
        'Resizing passport photos for UPSC Civil Services application forms that require 350×350px images between 20KB and 50KB.',
        'Compressing signature scans for IBPS bank recruitment portals requiring 140×60px signatures under 20KB.',
        'Preparing ID photos for university admission forms, visa applications, and government job portals with strict size requirements.',
        'Converting high-resolution smartphone photos into lightweight files suitable for slow-connection form uploads.',
      ],
    },
    faqs: [
      { question: 'Will my photo be saved on your servers?', answer: 'No. This tool runs 100% locally in your web browser using client-side JavaScript. Your photo never leaves your device — it is processed entirely in memory using the HTML5 Canvas API. No data is uploaded, stored, or transmitted to any server.' },
      { question: 'Why does the image quality change after compression?', answer: 'To fit strict government limits (like 20-50KB), the tool compresses the image by adjusting its JPEG quality level and resizing its dimensions. We use a binary search algorithm that iteratively tests different quality values to find the best possible quality that still fits under the maximum KB limit — maximizing clarity while meeting requirements.' },
      { question: 'What image formats are supported?', answer: 'You can upload JPG, PNG, or WebP images. For JPG input, the tool outputs a compressed JPG. For PNG input, it preserves the PNG format to maintain transparency. The final downloaded file is compatible with all government portals.' },
      { question: 'What if the output file is still too large or too small?', answer: 'If the output doesn\'t hit the exact target range, try uploading a smaller or larger original image. The compression algorithm works best when the original image is reasonably sized — very large originals (5000+ pixels) may compress differently than standard passport photos.' },
      { question: 'Can I use this tool offline?', answer: 'Yes! Since the entire tool runs in your browser with no server dependency, it works even without an internet connection after the page has loaded. This makes it perfect for use in exam centers or areas with poor connectivity.' },
    ],
  },
  'pdf-compressor': {
    guide: {
      title: 'What is the PDF Compressor Tool?',
      overview: 'The KagazKit PDF Compressor is a powerful online utility that reduces the file size of your PDF documents while maintaining readable quality. Many government portals, university admission forms, and corporate HR systems impose strict upload limits — often as low as 200KB or 500KB. Large scanned documents or multi-page PDFs regularly exceed these limits. Our tool uses industry-standard Ghostscript compression on our secure processing server to dramatically reduce PDF file sizes, making them suitable for any upload portal.',
      steps: [
        { step: 'Upload your PDF', description: 'Click the upload area or drag-and-drop your PDF file. The tool accepts files up to 10MB for stable processing.' },
        { step: 'Select compression level', description: 'Choose between different compression qualities depending on whether you need maximum reduction or better visual clarity.' },
        { step: 'Wait for processing', description: 'Your PDF is securely sent to our temporary processing server, compressed using Ghostscript, and returned to your browser.' },
        { step: 'Download compressed PDF', description: 'Review the before-and-after file sizes and download your newly compressed PDF file.' },
      ],
      features: [
        'Professional Ghostscript-based compression engine',
        'Dramatic file size reduction (often 50-80% smaller)',
        'Files are processed in memory and instantly deleted — never stored',
        'Perfect for government portal upload limits (200KB, 500KB, 1MB)',
        'Maintains text readability and document structure',
        'Supports multi-page PDF documents',
      ],
      useCases: [
        'Compressing scanned Aadhaar card, PAN card, or marksheet PDFs for government portal uploads that have 200KB or 500KB limits.',
        'Reducing large corporate reports or presentations for email attachments when your inbox has size restrictions.',
        'Shrinking multi-page academic transcripts for university admission portals with strict file size requirements.',
        'Preparing tax documents and financial statements for online filing systems that reject oversized uploads.',
      ],
    },
    faqs: [
      { question: 'Is my PDF stored on your server?', answer: 'No. While the PDF is temporarily transmitted to our processing server for Ghostscript compression, it is processed entirely in memory and instantly deleted after compression is complete. We never store, inspect, or retain your documents.' },
      { question: 'How much can the file size be reduced?', answer: 'Reduction depends on the original PDF content. Scanned image-heavy PDFs typically see 50-80% reduction. Text-heavy PDFs with minimal images may see 20-40% reduction. The tool always shows you the before-and-after sizes so you can evaluate the result.' },
      { question: 'Will compression affect the readability of my PDF?', answer: 'The compression algorithm is optimized to maintain readable quality for printed text and standard images. While some quality loss is inherent in compression, the output is designed to be perfectly acceptable for official submissions and document uploads.' },
      { question: 'What is the maximum file size I can upload?', answer: 'We recommend files under 10MB for the best experience. This limit prevents browser memory issues, especially on mobile devices and iOS Safari where large files can cause the browser tab to crash.' },
      { question: 'Can I compress password-protected PDFs?', answer: 'No, password-protected or encrypted PDFs cannot be processed because the compression engine needs to read and re-render the document contents. Remove the password protection first, then compress the file.' },
    ],
  },
  'merge-pdf': {
    guide: {
      title: 'What is the Merge PDF Tool?',
      overview: 'The KagazKit Merge PDF tool lets you combine multiple separate PDF files into a single unified document directly in your web browser. This is an essential utility for anyone who needs to consolidate scattered documents — such as combining your resume, cover letter, and certificates into one file for a job application. Unlike many online PDF mergers that upload your files to remote servers, our tool processes everything locally using the pdf-lib JavaScript library, ensuring your private documents never leave your device.',
      steps: [
        { step: 'Add PDF files', description: 'Click "Add Files" or drag-and-drop multiple PDFs into the upload area. You can add as many files as needed.' },
        { step: 'Arrange the order', description: 'Drag and reorder the files in the list to set the exact page sequence you want in the final merged document.' },
        { step: 'Click "Merge PDFs"', description: 'The tool combines all uploaded PDFs into a single file using client-side processing — nothing is uploaded to any server.' },
        { step: 'Download the merged file', description: 'Your combined PDF is ready for download. The original files remain untouched on your device.' },
      ],
      features: [
        '100% client-side processing — your documents never leave your browser',
        'Drag-and-drop reordering for precise page sequence control',
        'No file count limit — merge as many PDFs as your browser can handle',
        'Preserves original formatting, fonts, images, and hyperlinks',
        'Instant processing with no server upload delays',
        'Works offline after the page loads',
      ],
      useCases: [
        'Combining resume, cover letter, and certificates into a single PDF for job applications that accept only one file upload.',
        'Merging multiple scanned document pages (Aadhaar front+back, marksheets) into one consolidated file for government submissions.',
        'Consolidating separate invoice or receipt PDFs into a single expense report for accounting and reimbursement.',
        'Assembling multiple chapter drafts or research papers into a single manuscript PDF.',
      ],
    },
    faqs: [
      { question: 'Are my PDF files uploaded to a server?', answer: 'No. The merge operation happens 100% inside your web browser using the pdf-lib JavaScript library. Your sensitive documents — whether they are legal contracts, medical records, or financial statements — never leave your device.' },
      { question: 'Is there a limit on how many PDFs I can merge?', answer: 'There is no hard limit set by our tool. However, browser memory is finite. For very large merges (e.g., combining 50+ large PDFs totaling hundreds of megabytes), your browser may run out of memory. For typical use cases (2-20 files), the tool handles everything smoothly.' },
      { question: 'Will the formatting of my PDFs be preserved?', answer: 'Yes. The pdf-lib library preserves the original content of each PDF exactly as-is, including text, images, fonts, annotations, and hyperlinks. The merged file is simply a concatenation of the original pages in your specified order.' },
      { question: 'Can I rearrange the order of the files before merging?', answer: 'Absolutely. After uploading your files, you can drag and drop them into any order you prefer. The final merged document will follow the exact sequence you set.' },
      { question: 'Can I merge password-protected PDFs?', answer: 'No. If a PDF is encrypted or password-protected, the browser-based library cannot read its contents. You will need to remove the password protection from the file first before merging it with other documents.' },
    ],
  },
  'split-pdf': {
    guide: {
      title: 'What is the Split PDF Tool?',
      overview: 'The KagazKit Split PDF tool allows you to extract specific pages from a PDF document or split a large PDF into smaller files — all within your web browser. This is invaluable when you need to extract just a few pages from a large document, such as pulling a specific certificate page from a lengthy marksheet PDF, or separating individual chapters from a combined file. Powered by the pdf-lib library running entirely client-side, your documents are processed locally with zero server uploads.',
      steps: [
        { step: 'Upload your PDF', description: 'Click the upload area or drag-and-drop your PDF file. The tool will detect the total page count automatically.' },
        { step: 'Specify page range', description: 'Enter the pages you want to extract using range notation (e.g., "1-3, 5, 7-10"). The tool supports comma-separated page numbers and ranges.' },
        { step: 'Preview your selection', description: 'Review a preview of the selected pages to confirm you have the right content before splitting.' },
        { step: 'Download the split PDF', description: 'Click "Split & Download" to get a new PDF containing only your selected pages.' },
      ],
      features: [
        '100% local processing — your document never leaves your device',
        'Flexible page selection with ranges and individual page numbers',
        'Visual preview before splitting to confirm your selection',
        'Preserves original formatting, images, and text quality',
        'Handles multi-hundred-page documents efficiently',
        'No signup or login required',
      ],
      useCases: [
        'Extracting a specific certificate or marksheet page from a large combined academic PDF for job application uploads.',
        'Pulling individual chapters from a textbook PDF for easier reading and sharing.',
        'Separating the first page (cover letter) from a multi-page document when a portal only accepts single-page uploads.',
        'Creating smaller PDFs from large scanned documents to meet government portal file size limits.',
      ],
    },
    faqs: [
      { question: 'Is my PDF uploaded to any server?', answer: 'No. All splitting and page extraction happens 100% inside your web browser using client-side JavaScript. Your documents are processed in memory and never transmitted over the network.' },
      { question: 'How do I specify which pages to extract?', answer: 'Use standard page range notation: "1-5" extracts pages 1 through 5, "1,3,5" extracts only those specific pages, and "2-4, 7, 10-12" combines ranges with individual pages. The tool shows you the total page count to help you choose correctly.' },
      { question: 'Will splitting affect the quality of my PDF?', answer: 'No. The tool extracts pages exactly as they exist in the original PDF — no re-rendering or compression occurs. Text, images, fonts, and annotations are preserved perfectly.' },
      { question: 'Can I split a password-protected PDF?', answer: 'No. Encrypted PDFs cannot be read by the browser-based library. Remove the password protection first, then use the split tool.' },
      { question: 'Is there a page limit for the PDF I can upload?', answer: 'There is no hard limit, but very large PDFs (500+ pages or 50MB+) may be slow to process in the browser. For typical documents under 100 pages, the tool works instantly.' },
    ],
  },
  'image-to-pdf': {
    guide: {
      title: 'What is the Image to PDF Converter?',
      overview: 'The KagazKit Image to PDF Converter transforms your photos and scanned images into properly formatted PDF documents with precise file size control. This tool is specifically designed for Indian government and banking document submissions, where portals often require documents like Aadhaar cards, PAN cards, and signature scans in PDF format within strict KB limits. The converter handles multi-image uploads, automatic page arrangement, and intelligent compression to produce a PDF that meets your exact file size requirements.',
      steps: [
        { step: 'Upload images', description: 'Add one or more images (JPG, PNG, WebP) by clicking the upload area or dragging-and-dropping. Supports multiple files for multi-page PDFs.' },
        { step: 'Arrange page order', description: 'Drag and reorder your images to set the desired page sequence in the final PDF document.' },
        { step: 'Set KB limit (optional)', description: 'If your upload portal has a file size restriction, specify the maximum KB limit and the tool will automatically compress to fit.' },
        { step: 'Generate and download', description: 'Click "Convert to PDF" and download the resulting document. Processing happens entirely in your browser.' },
      ],
      features: [
        'Convert multiple images into a single multi-page PDF',
        'Strict KB limit enforcement for government portal compliance',
        'Supports JPG, PNG, and WebP image formats',
        '100% client-side — images never leave your device',
        'Automatic page sizing and orientation detection',
        'Drag-and-drop reordering for multi-page documents',
      ],
      useCases: [
        'Converting Aadhaar card photos (front and back) into a single PDF under 500KB for bank KYC verification.',
        'Creating a PAN card PDF scan within specific KB limits for income tax filing portals.',
        'Converting multiple document photographs into a single multi-page PDF for scholarship applications.',
        'Preparing photo ID documents as PDFs for visa and passport applications with strict format requirements.',
      ],
    },
    faqs: [
      { question: 'Are my images uploaded to a server?', answer: 'No. The entire conversion process happens in your web browser using client-side JavaScript libraries. Your images and the resulting PDF are processed locally in memory — nothing is ever transmitted to our servers.' },
      { question: 'Can I set a maximum file size for the PDF?', answer: 'Yes. You can specify a KB limit, and the tool will automatically compress images within the PDF to ensure the final file fits within your specified maximum. This is perfect for government portals that enforce strict upload size limits.' },
      { question: 'How many images can I convert at once?', answer: 'There is no hard limit. However, we recommend keeping the total images under 20 and total size under 10MB for optimal browser performance, especially on mobile devices.' },
      { question: 'Will the image quality be preserved?', answer: 'The tool preserves as much quality as possible while respecting your KB limit. If you set a very tight size restriction, some compression artifacts may appear. Without a KB limit, images are embedded at near-original quality.' },
      { question: 'What page size does the PDF use?', answer: 'The PDF pages are automatically sized to match the dimensions of each image, ensuring the content fills the page without distortion or unnecessary white space.' },
    ],
  },
  'tax-calculator': {
    guide: {
      title: 'What is the Income Tax Calculator?',
      overview: 'The KagazKit Income Tax Calculator helps Indian taxpayers compare their tax liability under both the Old Tax Regime and the New Tax Regime for the current financial year. Making the right choice between these two regimes can save you tens of thousands of rupees annually. Our calculator factors in your gross salary, Section 80C investments (PPF, ELSS, insurance), Section 80D health insurance deductions, HRA exemptions, and home loan interest — then instantly shows which regime results in lower taxes with a clear rupee-value savings figure.',
      steps: [
        { step: 'Enter your gross annual salary', description: 'Input your total Cost to Company (CTC) or gross annual income before any deductions.' },
        { step: 'Add your deductions', description: 'Enter your Section 80C investments, Section 80D health insurance premiums, HRA exemption amount, and home loan interest if applicable.' },
        { step: 'View instant comparison', description: 'The calculator automatically computes your tax under both regimes, applies standard deductions (₹50K old, ₹75K new), and shows the 87A rebate where applicable.' },
        { step: 'See the recommendation', description: 'A clear banner shows which regime saves you more money, with the exact rupee savings amount highlighted.' },
      ],
      features: [
        'Side-by-side comparison of Old vs New Tax Regime',
        'Automatically applies standard deduction and Section 87A rebate',
        'Supports all major deductions: 80C, 80D, HRA, Home Loan',
        'Real-time calculation as you adjust inputs',
        'Shows monthly tax impact alongside annual figures',
        'Completely private — no financial data leaves your device',
      ],
      useCases: [
        'Salaried employees choosing between Old and New regime before filing ITR to maximize their take-home pay.',
        'HR professionals helping employees understand their optimal tax regime during the declaration period.',
        'Freelancers and consultants estimating advance tax liability for quarterly payments.',
        'Recent graduates comparing how different salary packages translate to actual in-hand income after tax.',
      ],
    },
    faqs: [
      { question: 'What is the difference between Old and New Tax Regime?', answer: 'The Old Regime allows you to claim deductions like 80C, 80D, HRA, etc., which reduces your taxable income but has higher tax rates. The New Regime offers lower tax rates and a higher standard deduction (₹75k) but does not allow most Chapter VI-A deductions. The right choice depends on your specific deduction amounts.' },
      { question: 'Which regime is better for most people?', answer: 'If you have significant investments (like EPF, ELSS, PPF, Insurance premiums) exceeding ₹3-4 lakhs combined, and pay home loan interest or receive HRA, the Old Regime often saves more. For those with fewer deductions, the New Regime is generally better because of its lower slab rates and higher standard deduction.' },
      { question: 'What is the Section 87A rebate?', answer: 'Under Section 87A, if your taxable income is below a certain threshold, the government gives you a tax rebate. In the New Regime (FY 2024-25), it makes income up to ₹12.75 lakh effectively tax-free. In the Old Regime, it applies up to ₹5 lakh taxable income.' },
      { question: 'Does this calculator include cess?', answer: 'Yes. The calculator automatically adds the mandatory 4% Health and Education Cess on the computed tax amount, giving you the final accurate tax liability figure.' },
      { question: 'Is my salary data sent to any server?', answer: 'No. All tax calculations run 100% locally in your browser using JavaScript. Your income, deduction amounts, and tax results are never transmitted to or stored on any server. Your financial data stays completely private.' },
    ],
  },
  'sip-calculator': {
    guide: {
      title: 'What is the SIP Calculator?',
      overview: 'The KagazKit SIP (Systematic Investment Plan) Calculator helps you project the future value of regular monthly investments in mutual funds or index funds. SIP investing is one of the most popular and disciplined wealth-building strategies in India, allowing you to invest a fixed amount monthly and benefit from rupee cost averaging and the exponential power of compound interest. Our calculator also includes a Step-Up SIP feature, which models annual increases in your monthly contribution — aligning your investment growth with your rising income over time.',
      steps: [
        { step: 'Set monthly SIP amount', description: 'Use the slider to set your planned monthly investment amount (₹500 to ₹1,00,000).' },
        { step: 'Set expected return rate', description: 'Enter the expected annual return rate based on the fund type — equity funds typically yield 10-15%, debt funds 6-8%.' },
        { step: 'Set investment duration', description: 'Choose how many years you plan to continue investing — longer durations show dramatically higher compounding effects.' },
        { step: 'Set annual step-up percentage', description: 'If you plan to increase your SIP amount each year (e.g., by 10% as your salary grows), set the step-up percentage.' },
      ],
      features: [
        'Step-Up SIP modeling for realistic income-linked growth',
        'Clear breakdown of invested amount vs returns gained',
        'Real-time calculation as you adjust sliders',
        'Supports investment horizons up to 40 years',
        'Shows the dramatic impact of compounding over time',
        'No financial data is sent to any server',
      ],
      useCases: [
        'Planning long-term retirement savings by visualizing how monthly SIP contributions grow into a large corpus over 20-30 years.',
        'Comparing different mutual fund return scenarios (10% vs 12% vs 15%) to set realistic financial expectations.',
        'Understanding how a 10% annual step-up in SIP contributions can double your final corpus compared to a flat SIP.',
        'Setting financial goals for children\'s education or marriage by working backwards from a target amount.',
      ],
    },
    faqs: [
      { question: 'What is a Step-Up SIP?', answer: 'A Step-Up SIP automatically increases your monthly investment amount by a specific percentage every year. For example, if you start with ₹5,000/month and set a 10% step-up, your SIP becomes ₹5,500 in year 2, ₹6,050 in year 3, and so on. This aligns your investments with your growing income and significantly boosts your final corpus through compounding.' },
      { question: 'Are the returns shown guaranteed?', answer: 'No. SIP returns in mutual funds are subject to market risks and volatility. The expected return rate used in this calculator is an estimation based on historical long-term data. Equity mutual funds have historically returned around 10-15% over long periods (10+ years), but past performance does not guarantee future results.' },
      { question: 'Is this calculator safe to use with my financial data?', answer: 'Yes, 100% safe. This calculator runs entirely in your web browser using client-side JavaScript. No investment amounts, return rates, or projected figures are ever sent to our servers or stored anywhere. Your financial planning remains completely private.' },
      { question: 'What is the ideal SIP duration for wealth creation?', answer: 'The longer the better. Compound interest shows its true power over extended periods. A 10-year SIP will grow well, but a 20-30 year SIP will generate returns that are many multiples of your invested amount. Starting early, even with small amounts, is the key to wealth creation through SIP.' },
      { question: 'How accurate is this calculator?', answer: 'The calculator uses standard financial mathematics for compound interest with monthly compounding. While the math is precise, the actual returns from mutual funds will vary based on market performance, fund management, and economic conditions. Use this as a planning tool, not a guarantee.' },
    ],
  },
  'emi-calculator': {
    guide: {
      title: 'What is the EMI Calculator?',
      overview: 'The KagazKit EMI (Equated Monthly Installment) Calculator helps you determine the exact monthly payment for any loan — whether it is a home loan, car loan, personal loan, or education loan. By inputting the principal amount, annual interest rate, and loan tenure, the calculator instantly shows your monthly EMI, total interest payable, and total repayment amount. The visual principal-vs-interest breakdown bar helps you understand exactly how much of your money goes toward paying off the loan versus enriching the bank.',
      steps: [
        { step: 'Enter the loan amount', description: 'Input the total principal amount you plan to borrow from the bank or financial institution.' },
        { step: 'Set the interest rate', description: 'Enter the annual interest rate offered by your lender. You can try different rates to compare offers from multiple banks.' },
        { step: 'Choose the loan tenure', description: 'Use the slider to select the repayment period in years. Longer tenures mean lower EMI but higher total interest.' },
        { step: 'Review the results', description: 'The calculator instantly displays your monthly EMI, total interest cost, and a visual breakdown of principal vs interest proportions.' },
      ],
      features: [
        'Instant EMI calculation using the standard financial formula',
        'Visual principal vs interest breakdown bar chart',
        'Real-time updates as you adjust any input parameter',
        'Supports loan amounts up to crores with precise decimal rates',
        'Shows both monthly EMI and total cost of the loan',
        'All calculations happen locally — your financial data stays private',
      ],
      useCases: [
        'Comparing home loan EMIs across different banks by trying various interest rates for the same loan amount and tenure.',
        'Planning household budgets by understanding exactly how much of your monthly income will go toward loan repayments.',
        'Evaluating whether to take a shorter tenure (higher EMI, less interest) or longer tenure (lower EMI, more interest) for a car loan.',
        'Estimating the total cost of an education loan before committing to a study-abroad program.',
      ],
    },
    faqs: [
      { question: 'How is EMI calculated?', answer: 'EMI is calculated using the standard financial formula: EMI = P × R × (1+R)^N / [(1+R)^N - 1], where P is the Principal loan amount, R is the monthly interest rate (annual rate divided by 12 and by 100), and N is the total number of monthly installments (years × 12). This formula ensures each payment covers both interest and principal repayment.' },
      { question: 'Why is the total interest sometimes higher than the loan amount?', answer: 'For long-term home loans (20 or 30 years), the power of compound interest works against you. Because you are paying the loan over decades, the accumulated interest often surpasses the original borrowed amount. Our visual breakdown bar clearly shows exactly how much of your money goes to the bank as pure interest vs actual principal repayment.' },
      { question: 'Does a lower EMI always mean a better deal?', answer: 'Not necessarily. A lower EMI usually means a longer loan tenure, which results in significantly more total interest paid over the life of the loan. Sometimes paying a slightly higher EMI for a shorter tenure saves you lakhs in total interest. Use the calculator to compare both scenarios.' },
      { question: 'Is my financial data secure?', answer: 'Yes. All EMI calculations are performed entirely in your web browser using client-side JavaScript. Your loan amount, interest rate, and calculated results are never sent to our servers. Your financial planning data remains completely private.' },
      { question: 'Can I use this for car loans and personal loans too?', answer: 'Absolutely. The EMI formula is universal for all types of reducing-balance loans. Whether you are calculating for a home loan, car loan, personal loan, education loan, or any other amortized loan product, this calculator gives you accurate results.' },
    ],
  },
  'salary-calculator': {
    guide: {
      title: 'What is the In-Hand Salary Calculator?',
      overview: 'The KagazKit In-Hand Salary Calculator converts your CTC (Cost to Company) into the actual monthly take-home salary you receive in your bank account. In India, the CTC mentioned in an offer letter includes many components — Basic Pay, HRA, Special Allowances, PF contributions, and taxes — that significantly reduce the actual amount you receive. This calculator breaks down your CTC into every component, deducts PF and estimated income tax, and shows your exact in-hand monthly salary so you can make informed career decisions.',
      steps: [
        { step: 'Enter your annual CTC', description: 'Input the total Cost to Company mentioned in your offer letter or salary structure.' },
        { step: 'Add bonus amount (if any)', description: 'Enter any annual performance bonus or variable pay component that is part of your CTC.' },
        { step: 'Select tax regime', description: 'Choose Old or New tax regime. The calculator applies the appropriate tax slabs and deductions automatically.' },
        { step: 'Review the breakdown', description: 'See a complete breakdown of Basic, HRA, Special Allowance, PF deduction, income tax, and your final monthly in-hand amount.' },
      ],
      features: [
        'Complete CTC to take-home salary breakdown',
        'Supports both Old and New tax regime calculations',
        'Automatically calculates PF (employee + employer contribution)',
        'Shows Basic Pay, HRA, and Special Allowance split',
        'Includes income tax estimation with standard deduction',
        '100% client-side — your salary data stays private',
      ],
      useCases: [
        'Evaluating a new job offer by understanding how much of the CTC you will actually take home each month after all deductions.',
        'Comparing two competing job offers with different CTC structures to see which gives a higher in-hand salary.',
        'Planning monthly household budgets based on the actual amount that gets credited to your bank account.',
        'Understanding PF contribution splits for retirement planning and verifying your payslip components.',
      ],
    },
    faqs: [
      { question: 'Why is my in-hand salary so much less than my CTC?', answer: 'CTC (Cost to Company) includes the employer\'s contribution to your Provident Fund (12% of Basic), gratuity provisions, insurance premiums, and other benefits that don\'t appear in your monthly bank credit. Additionally, income tax is deducted at source (TDS) from your monthly salary. These combined deductions typically reduce your take-home to 65-80% of your CTC.' },
      { question: 'How does the calculator split CTC into components?', answer: 'The calculator uses standard Indian payroll norms: Basic Pay is typically 40-50% of CTC, HRA is 40-50% of Basic, and the remainder is Special Allowance. PF deduction is 12% of Basic from both employee and employer. The exact split may vary between companies, but this gives an accurate estimate.' },
      { question: 'Which tax regime should I choose?', answer: 'If you have significant deductions under 80C (₹1.5L), 80D, HRA, and home loan interest totaling ₹3-4L+, the Old Regime may be better. If your deductions are minimal, the New Regime with its lower tax rates and ₹75K standard deduction is usually more favorable.' },
      { question: 'Is my salary data stored anywhere?', answer: 'No. All calculations happen entirely in your web browser. Your CTC, deduction details, and computed in-hand salary are never transmitted to or stored on any server. Your compensation data remains completely confidential.' },
      { question: 'Can I use this for freelance or business income?', answer: 'This calculator is designed specifically for salaried employees with a standard CTC structure. Freelancers and business owners have different tax computation methods and should use an income tax calculator or consult a CA for accurate projections.' },
    ],
  },
  'gst-calculator': {
    guide: {
      title: 'What is the GST Calculator?',
      overview: 'The KagazKit GST (Goods and Services Tax) Calculator instantly computes GST on any amount for all standard Indian tax slabs — 5%, 12%, 18%, and 28%. It supports both forward calculation (adding GST to a base price) and reverse calculation (extracting the base price from a GST-inclusive amount). The tool also breaks down the total tax into CGST and SGST components for intra-state transactions, making it invaluable for invoice generation, bill verification, and daily business accounting.',
      steps: [
        { step: 'Enter the amount', description: 'Type the base price (exclusive of GST) or the final price (inclusive of GST) depending on your calculation mode.' },
        { step: 'Select calculation mode', description: 'Choose "Add GST" to calculate tax on a base price, or "Remove GST" to extract the original price from a tax-inclusive amount.' },
        { step: 'Select GST rate', description: 'Pick the applicable tax slab — 5%, 12%, 18%, or 28% — based on the goods or services category.' },
        { step: 'View the breakdown', description: 'See the base amount, CGST, SGST (or IGST), and total amount instantly calculated with precise decimal accuracy.' },
      ],
      features: [
        'Supports all 4 standard GST slabs: 5%, 12%, 18%, 28%',
        'Forward (add) and reverse (remove) GST calculation',
        'Automatic CGST/SGST split for intra-state billing',
        'Real-time calculation as you type',
        'Precise to 2 decimal places for accounting accuracy',
        'No data sent to servers — completely private',
      ],
      useCases: [
        'Business owners generating invoices who need to calculate the correct GST amount and CGST/SGST split for billing customers.',
        'Consumers verifying whether the GST charged on a restaurant bill or retail purchase is correct for the applicable slab.',
        'Accountants performing reverse GST calculations to extract pre-tax amounts from inclusive invoices for bookkeeping.',
        'E-commerce sellers calculating the correct selling price after adding 18% GST to their base product cost.',
      ],
    },
    faqs: [
      { question: 'What is the difference between Adding and Removing GST?', answer: 'Adding GST means calculating the tax amount on top of a base price (Exclusive of tax) — the result is the final billing amount. Removing GST means calculating backwards from a final total price to find what the original base price was before the tax was applied (Inclusive of tax) — useful for verifying invoices and extracting pre-tax costs.' },
      { question: 'How is CGST and SGST calculated?', answer: 'For intra-state sales (within the same state), the total GST amount is divided equally into two halves: Central GST (CGST) and State GST (SGST). For example, an 18% GST becomes 9% CGST and 9% SGST. For inter-state sales, the full amount is charged as IGST (Integrated GST).' },
      { question: 'What are the standard GST slabs in India?', answer: 'The primary GST slabs currently active in India are: 5% (essential goods like packaged food, economy hotel rooms), 12% (processed food, business class flights), 18% (most services, electronics, financial services), and 28% (luxury items, automobiles, aerated beverages). Some items have 0% GST (basic necessities like fresh food and healthcare).' },
      { question: 'Can I use this for IGST calculations?', answer: 'For inter-state transactions, the total GST amount shown is your IGST amount (since IGST = CGST + SGST at the same total rate). Simply use the total GST figure as your IGST value.' },
      { question: 'Is my business pricing data secure?', answer: 'Absolutely. All GST calculations run 100% in your browser. No amounts, rates, or results are ever sent to our servers. Your confidential pricing and billing data remains completely private.' },
    ],
  },
  'epf-calculator': {
    guide: {
      title: 'What is the EPF Calculator?',
      overview: 'The KagazKit EPF (Employees\' Provident Fund) Calculator projects your total PF corpus at retirement based on your current basic salary, expected annual salary increments, and the current EPF interest rate. The EPF is a mandatory savings scheme for salaried employees in India where both the employee and employer contribute 12% of basic salary each month. Over a 20-30 year career, this corpus — combined with compound interest — grows into a substantial retirement fund. Our calculator helps you visualize this long-term growth.',
      steps: [
        { step: 'Enter your current monthly basic salary', description: 'Input the basic component of your monthly salary (typically 40-50% of your gross salary).' },
        { step: 'Set your current age and retirement age', description: 'These determine the total contribution period in years. The default retirement age is 58.' },
        { step: 'Set expected annual salary increment', description: 'Enter the percentage by which your basic salary is expected to increase annually (typically 5-10% in India).' },
        { step: 'Review the projection', description: 'See your total employee contribution, employer contribution, compound interest earned, and final EPF corpus at retirement.' },
      ],
      features: [
        'Projects EPF corpus with annual salary increments factored in',
        'Calculates both employee (12%) and employer (3.67% to EPF) contributions',
        'Uses EPFO-declared interest rate with annual compounding',
        'Shows invested principal vs interest earned breakdown',
        'Supports custom retirement age and increment rates',
        'All calculations run locally — salary data stays private',
      ],
      useCases: [
        'Estimating your total retirement corpus from EPF contributions to plan supplementary investments in NPS or mutual funds.',
        'Understanding how annual salary increments compound your PF balance over a 25-30 year career span.',
        'Comparing the impact of different EPF interest rates (8.15%, 8.25%, 8.50%) on your final corpus over the long term.',
        'Planning early retirement by calculating the minimum PF corpus needed alongside other savings.',
      ],
    },
    faqs: [
      { question: 'How does EPF interest compounding work?', answer: 'EPF interest is computed on a monthly running balance but compounded annually. The EPFO declares an annual interest rate (currently around 8.15-8.25%), and this rate is applied to your cumulative balance including previous years\' interest. Over decades, this compounding creates substantial wealth.' },
      { question: 'What is the difference between employee and employer PF contribution?', answer: 'Both employee and employer contribute 12% of basic salary. However, the employer\'s 12% is split: 3.67% goes to EPF (your PF account), and 8.33% goes to EPS (Employees\' Pension Scheme, capped at ₹15,000 basic). Our calculator models the EPF portion accurately.' },
      { question: 'Is EPF taxable?', answer: 'EPF falls under the EEE (Exempt-Exempt-Exempt) category if withdrawn after 5 years of continuous service. Your contributions get Section 80C deduction, the interest earned is tax-free, and the maturity amount is tax-free — making it one of the most tax-efficient savings instruments in India.' },
      { question: 'Can I withdraw EPF before retirement?', answer: 'Partial withdrawals are allowed for specific purposes like home purchase, medical emergencies, or marriage after completing certain years of service. Full withdrawal is permitted after 2 months of unemployment or at retirement (age 58). Early withdrawal before 5 years of service may attract TDS.' },
      { question: 'Is my salary data secure on this tool?', answer: 'Yes. All EPF projections are calculated entirely in your web browser. Your basic salary, age, and projected corpus figures are never sent to or stored on any server. Your employment and financial data remains completely private.' },
    ],
  },
  'deposit-calculator': {
    guide: {
      title: 'What is the FD & RD Calculator?',
      overview: 'The KagazKit Deposit Calculator helps you project the maturity value and interest earned on Fixed Deposits (FD) and Recurring Deposits (RD) based on standard Indian banking formulas. FDs involve a one-time lump sum investment for a fixed period, while RDs allow monthly contributions over a fixed tenure. Both are popular low-risk savings instruments in India. Our calculator uses quarterly compounding for FDs and the Future Value of Annuity formula for RDs to give you accurate projections.',
      steps: [
        { step: 'Select deposit type', description: 'Choose between Fixed Deposit (lump sum investment) or Recurring Deposit (monthly contributions).' },
        { step: 'Enter the amount', description: 'For FD, enter the one-time investment amount. For RD, enter the monthly deposit amount.' },
        { step: 'Set interest rate and tenure', description: 'Enter the annual interest rate offered by your bank and the deposit duration in years.' },
        { step: 'View maturity projection', description: 'See the total invested amount, interest earned, and maturity value with a clear breakdown.' },
      ],
      features: [
        'Supports both Fixed Deposit and Recurring Deposit calculations',
        'Quarterly compounding for FD (standard Indian banking practice)',
        'Future Value of Annuity formula for RD accuracy',
        'Clear principal vs interest breakdown',
        'Compare different rates and tenures side-by-side',
        'All calculations run privately in your browser',
      ],
      useCases: [
        'Comparing FD interest rates across different banks to find the best return for a lump sum savings amount.',
        'Planning monthly RD contributions to save for a specific goal like a vacation, wedding, or emergency fund.',
        'Senior citizens evaluating which bank offers the best FD rate with the highest quarterly compounded return.',
        'Estimating TDS liability on FD interest exceeding ₹40,000/year (₹50,000 for senior citizens).',
      ],
    },
    faqs: [
      { question: 'What is the difference between FD and RD?', answer: 'A Fixed Deposit (FD) is a one-time lump sum investment made for a specific period at a fixed interest rate. A Recurring Deposit (RD) allows you to deposit a fixed amount every month for a specific period. Both offer guaranteed, predetermined returns — FDs suit those with a lump sum to invest, while RDs suit regular monthly savers.' },
      { question: 'How is Fixed Deposit interest calculated?', answer: 'In India, most banks compound Fixed Deposit interest quarterly. This means the interest earned in the first quarter is added to the principal, and you earn interest on the new total in subsequent quarters. Our calculator uses this standard quarterly compounding formula.' },
      { question: 'Are FD and RD returns taxable?', answer: 'Yes, the interest earned from both FDs and RDs is fully taxable according to your income tax slab. Banks deduct TDS (Tax Deducted at Source) if the interest exceeds ₹40,000 per year (₹50,000 for senior citizens). You can claim this TDS credit when filing your ITR.' },
      { question: 'Can I break an FD before maturity?', answer: 'Yes, most banks allow premature withdrawal of FDs, but they typically charge a penalty of 0.5-1% on the interest rate. Some banks also offer sweep-in FDs that auto-break only the required portion, preserving interest on the remaining balance.' },
      { question: 'Is my financial data secure?', answer: 'All deposit calculations run entirely in your web browser. Your investment amounts, interest rates, and projected returns are never sent to any server. Your financial planning data remains completely private and secure.' },
    ],
  },
  'loan-prepayment': {
    guide: {
      title: 'What is the Loan Prepayment Calculator?',
      overview: 'The KagazKit Loan Prepayment Calculator shows you exactly how much interest you can save by making extra payments on your loan. When you make a lump sum prepayment or increase your monthly EMI, the principal reduces faster, which dramatically cuts down the total interest paid over the loan lifetime. This calculator compares your loan with and without prepayments — showing the interest saved, tenure reduction, and effective savings that could amount to lakhs of rupees on a typical home loan.',
      steps: [
        { step: 'Enter your loan details', description: 'Input the original loan amount, annual interest rate, and total loan tenure in years.' },
        { step: 'Add prepayment details', description: 'Specify the lump sum prepayment amount and when you plan to make it (after how many months/years).' },
        { step: 'Compare scenarios', description: 'The calculator shows a side-by-side comparison of total interest with and without prepayment.' },
        { step: 'Review your savings', description: 'See the exact rupee amount saved in interest and the number of months/years the loan tenure is reduced by.' },
      ],
      features: [
        'Compare loan cost with and without prepayments',
        'Shows exact interest savings in rupees',
        'Calculates tenure reduction from prepayment',
        'Supports lump sum and recurring extra payment scenarios',
        'Real-time calculation as you adjust inputs',
        'Completely private — your loan data stays in your browser',
      ],
      useCases: [
        'Home loan borrowers deciding whether to use a bonus or windfall to prepay their mortgage and how much interest it would save.',
        'Comparing the benefit of increasing monthly EMI by ₹5,000-10,000 vs making a one-time lump sum prepayment.',
        'Planning optimal prepayment timing — understanding whether prepaying early in the loan tenure saves more than prepaying later.',
        'Evaluating whether to invest surplus funds in mutual funds or use them to prepay a home loan based on interest rate comparison.',
      ],
    },
    faqs: [
      { question: 'How does loan prepayment save interest?', answer: 'When you make a prepayment, the lump sum directly reduces the outstanding principal. Since interest is calculated on the remaining principal, a lower principal means lower interest charges in every subsequent EMI. The earlier you prepay, the more interest you save because there are more remaining EMIs that benefit from the reduced principal.' },
      { question: 'Is it better to reduce EMI or reduce tenure after prepayment?', answer: 'Reducing tenure (keeping the same EMI) saves significantly more total interest because you pay off the loan faster. Reducing EMI (keeping the same tenure) gives you immediate monthly cash flow relief but results in more total interest paid. For maximum savings, choose tenure reduction.' },
      { question: 'Are there penalties for prepaying a loan?', answer: 'For home loans with floating interest rates, RBI guidelines prohibit banks from charging prepayment penalties. For fixed-rate home loans and personal loans, banks may charge 2-4% of the prepaid amount as a penalty. Always check your loan agreement before prepaying.' },
      { question: 'When is the best time to prepay a loan?', answer: 'The earlier the better. In the initial years of a loan, a larger portion of your EMI goes toward interest (not principal). Prepaying early dramatically reduces the interest component for the remaining tenure. Prepaying in the last few years of a loan saves relatively less because most interest has already been paid.' },
      { question: 'Is my loan data secure?', answer: 'Yes. All calculations happen entirely in your web browser. Your loan amount, interest rate, prepayment amounts, and computed savings are never sent to any server. Your financial information remains completely private.' },
    ],
  },
  'qr-code-generator': {
    guide: {
      title: 'What is the QR Code Generator?',
      overview: 'The KagazKit QR Code Generator creates high-quality, scannable QR codes instantly from any text, URL, phone number, or custom content. QR codes (Quick Response codes) are two-dimensional barcodes that can be scanned by smartphone cameras to instantly open websites, display text, or trigger actions. Our generator creates static QR codes that never expire, require no subscription, and encode the data directly into the image — meaning they work forever without any server dependency.',
      steps: [
        { step: 'Enter your content', description: 'Type or paste the URL, text message, phone number, or any content you want to encode into the QR code.' },
        { step: 'Customize appearance', description: 'Choose custom foreground and background colors to match your brand or design requirements.' },
        { step: 'Adjust the size', description: 'Use the slider to set the QR code size from 128px to 512px depending on your intended use (digital or print).' },
        { step: 'Download the PNG', description: 'Click "Download PNG" to save a high-resolution QR code image to your device, ready for printing or digital use.' },
      ],
      features: [
        'Instant QR code generation with live preview',
        'Custom foreground and background colors',
        'Adjustable size from 128px to 512px',
        'High error correction level (H) for reliable scanning',
        'Downloads as high-resolution PNG image',
        '100% client-side — your data never touches a server',
      ],
      useCases: [
        'Creating QR codes for restaurant digital menus that link to an online menu page when scanned by diners.',
        'Generating business card QR codes that link to your LinkedIn profile, portfolio website, or contact vCard.',
        'Adding QR codes to product packaging, flyers, or posters for instant access to product information or promotional pages.',
        'Creating WiFi sharing QR codes for guests at events, offices, or home networks.',
      ],
    },
    faqs: [
      { question: 'Is this QR code generator completely free?', answer: 'Yes, it is 100% free with no usage limits. You can generate unlimited QR codes, and they are never watermarked. There are no premium tiers, subscriptions, or hidden charges.' },
      { question: 'Do the QR codes expire?', answer: 'No, they never expire. These are static QR codes — the data (URL, text, etc.) is encoded directly into the image pattern. Since the code itself contains the information, it will work forever as long as the linked URL remains active. There is no server dependency.' },
      { question: 'Is my data sent to a server to generate the code?', answer: 'No. The QR code is generated entirely inside your web browser using the qrcode.react library. Nothing you type — whether it is a URL, personal text, phone number, or WiFi password — is ever uploaded to or stored on our servers.' },
      { question: 'What size should I use for printing?', answer: 'For print materials like business cards, use at least 256px or higher. For large posters or banners, use the maximum 512px size. The downloaded PNG can be scaled up without losing scannability because QR codes are inherently pixel-based patterns.' },
      { question: 'Why is the error correction level set to "H"?', answer: 'We use the highest error correction level (H = 30% recovery), which means the QR code can still be scanned even if up to 30% of it is damaged, obscured, or partially covered. This ensures maximum reliability in real-world scanning conditions.' },
    ],
  },
  'password-generator': {
    guide: {
      title: 'What is the Password Generator?',
      overview: 'The KagazKit Password Generator creates cryptographically secure, truly random passwords using your browser\'s built-in Web Crypto API (window.crypto.getRandomValues). Unlike pseudo-random generators that use predictable algorithms, the Web Crypto API provides true cryptographic randomness sourced from your operating system\'s entropy pool. This makes the generated passwords extremely resistant to brute-force attacks, dictionary attacks, and pattern-based cracking attempts. You can customize the length, character sets, and complexity to meet any password policy requirements.',
      steps: [
        { step: 'Set password length', description: 'Use the slider to choose a length between 8 and 64 characters. Longer passwords are exponentially harder to crack.' },
        { step: 'Select character types', description: 'Toggle uppercase letters (A-Z), lowercase letters (a-z), numbers (0-9), and special symbols (!@#$%) on or off based on your needs.' },
        { step: 'Generate the password', description: 'Click "Generate" to create a new random password. You can regenerate as many times as you like until you find one you prefer.' },
        { step: 'Copy to clipboard', description: 'Click the copy button to instantly copy the password to your clipboard for pasting into registration or login forms.' },
      ],
      features: [
        'True cryptographic randomness via window.crypto.getRandomValues()',
        'Customizable length from 8 to 64 characters',
        'Toggle uppercase, lowercase, numbers, and symbols independently',
        'Visual password strength indicator',
        'One-click copy to clipboard',
        'Zero network requests — password never leaves your device',
      ],
      useCases: [
        'Creating unique, strong passwords for each online account to prevent credential stuffing attacks.',
        'Generating passwords that comply with strict corporate IT policies requiring specific character types and minimum lengths.',
        'Creating secure passphrases for encrypting sensitive files, SSH keys, or cryptocurrency wallets.',
        'Replacing weak, reused passwords across banking, email, and social media accounts with unique strong ones.',
      ],
    },
    faqs: [
      { question: 'Is the password truly random?', answer: 'Yes. We use the browser\'s native Web Crypto API (window.crypto.getRandomValues()), which provides cryptographically secure pseudorandom numbers sourced from your operating system\'s hardware entropy pool. This is the same randomness source used by banks and security software — not the weak Math.random() that many other generators use.' },
      { question: 'Is my generated password sent to any server?', answer: 'Absolutely not. The password is generated entirely within your browser\'s local memory using JavaScript. No network requests are made during generation. The password exists only in your browser tab until you copy it or navigate away — it is never transmitted, logged, or stored anywhere.' },
      { question: 'How long should my password be?', answer: 'For most accounts, 16+ characters is considered very strong. For high-security applications (banking, crypto wallets), use 24+ characters with all character types enabled. Every additional character exponentially increases the time needed for brute-force attacks — a 20-character password with all character types would take billions of years to crack.' },
      { question: 'Should I include special symbols?', answer: 'Yes, when the service allows it. Special symbols dramatically increase the character set size, making passwords much harder to crack. A 12-character password with only lowercase letters has ~95 billion combinations, but adding uppercase, numbers, and symbols increases it to ~19 sextillion combinations.' },
      { question: 'Can I use this with a password manager?', answer: 'Absolutely. Generate a strong password here, copy it, and paste it into your password manager (like Bitwarden, 1Password, or KeePass). This way you only need to remember one master password while having unique, strong passwords for every account.' },
    ],
  },
  'age-calculator': {
    guide: {
      title: 'What is the Age Calculator?',
      overview: 'The KagazKit Age Calculator computes your exact chronological age in years, months, and days as of any specific cutoff date. This tool is specifically designed for Indian government exam applicants who need precise age calculations for eligibility verification. Exams like UPSC, SSC CGL, IBPS PO, Railway RRB, and State PSC have strict age limits (e.g., 21-32 years) calculated as of a specific cutoff date mentioned in the notification. Being even one day outside the limit means automatic rejection — making precise calculation critical.',
      steps: [
        { step: 'Enter your date of birth', description: 'Select your date of birth using the date picker. This is the starting date for the age calculation.' },
        { step: 'Enter the cutoff date', description: 'Enter the specific "Age As Of" date mentioned in the exam notification or application form. This is the date on which your age will be calculated.' },
        { step: 'Click "Calculate Exact Age"', description: 'The tool computes the precise difference accounting for leap years, varying month lengths, and calendar boundaries.' },
        { step: 'Review your exact age', description: 'See your age displayed in years, months, and days — the exact format required by most government application forms.' },
      ],
      features: [
        'Exact age calculation in years, months, and days',
        'Handles leap years and varying month lengths correctly',
        'Custom cutoff date for exam-specific eligibility checks',
        'Instant calculation with no server processing',
        'Perfect for UPSC, SSC, IBPS, and Railway exam forms',
        'Your date of birth is never sent to any server',
      ],
      useCases: [
        'UPSC Civil Services aspirants verifying their age eligibility against the notification cutoff date before applying.',
        'SSC CGL and CHSL candidates checking whether they fall within the 18-32 age bracket as of the exam cutoff date.',
        'IBPS PO and Clerk applicants confirming age eligibility (20-30 years) for banking recruitment exams.',
        'Railway RRB and State PSC candidates calculating their exact age for category-wise age limit verification.',
      ],
    },
    faqs: [
      { question: 'Why do I need to calculate my exact age in days?', answer: 'Most Indian government exams (UPSC, SSC, Banking, Railway) have strict age criteria. They require you to be within a specific age range (e.g., 21 to 32 years) strictly as of a given cutoff date mentioned in their official notification. Being even one day older or younger than the limit can lead to application rejection. Precise day-level calculation is therefore critical.' },
      { question: 'How is the exact age calculated?', answer: 'Our tool uses calendar math to calculate the precise difference between your Date of Birth and the target cutoff date. It correctly accounts for leap years (February 29th), months with 28, 29, 30, or 31 days, and year boundaries — ensuring mathematically accurate results for official documentation.' },
      { question: 'Is my date of birth saved or tracked?', answer: 'No. The KagazKit Age Calculator runs 100% locally in your browser using client-side JavaScript. Your date of birth and cutoff dates are processed in memory and never sent to any server, stored in any database, or tracked in any way. Complete privacy is guaranteed.' },
      { question: 'What if the start date is after the end date?', answer: 'The calculator will display an error message asking you to correct the dates. Your Date of Birth must be before the cutoff date for a valid age calculation.' },
      { question: 'Can I use this for age verification other than exams?', answer: 'Absolutely. While designed primarily for government exam eligibility, this calculator works perfectly for any age computation — passport applications, visa age requirements, insurance age verification, school admission age criteria, or simply knowing your exact age on any specific date.' },
    ],
  },
  'date-calculator': {
    guide: {
      title: 'What is the Date Calculator?',
      overview: 'The KagazKit Date Calculator computes the exact duration between any two dates, displaying the result in multiple formats — total days, weeks and days, and a full years-months-days breakdown. This is useful for project timeline planning, contract duration verification, event planning, and academic deadline tracking. The tool also includes an option to include the end date in the count, which is important for scenarios like calculating the total days of a multi-day event or the duration of a notice period.',
      steps: [
        { step: 'Select the start date', description: 'Choose the beginning date of the period you want to measure using the date picker.' },
        { step: 'Select the end date', description: 'Choose the ending date. The tool automatically handles cases where the start date is after the end date by swapping them.' },
        { step: 'Toggle end date inclusion', description: 'Check "Include end date" if you want to count the last day as a full day (adds 1 to the total count). Useful for multi-day event durations.' },
        { step: 'Click "Calculate Duration"', description: 'View the total days, weeks + remaining days, and full years/months/days breakdown instantly.' },
      ],
      features: [
        'Multiple output formats: total days, weeks+days, years+months+days',
        'Option to include or exclude the end date in the count',
        'Automatically handles date order (swaps if start > end)',
        'Correctly accounts for leap years and variable month lengths',
        'Instant calculation with no server dependency',
        'No dates are stored or transmitted — complete privacy',
      ],
      useCases: [
        'Calculating the exact number of working days between a project start date and deadline for resource planning.',
        'Verifying the duration of a rental lease, employment contract, or subscription period in precise days.',
        'Computing notice periods for job resignations — confirming exactly how many days your 2-month notice covers.',
        'Planning event timelines by knowing the exact days remaining until a wedding, exam date, or travel departure.',
      ],
    },
    faqs: [
      { question: 'Why would I include the end date?', answer: 'By default, calendar math counts the number of midnights between two dates. For example, Monday to Tuesday is 1 day. If you are calculating the total duration of a 2-day event that runs all Monday and all Tuesday, you need to "include the end date" to get 2 days. This is also relevant for computing inclusive periods like employment duration.' },
      { question: 'Does this tool account for leap years?', answer: 'Yes, our calculator automatically accounts for leap years and the varying number of days in different months (28, 29, 30, or 31). It relies on accurate native browser date parsing, which handles all calendar edge cases correctly — including century leap year rules.' },
      { question: 'Can I calculate the date that is X days from today?', answer: 'This particular tool calculates the duration between two known dates. For adding or subtracting days from a date, you would manually enter today\'s date and your target date. The tool gives you the breakdown in multiple formats.' },
      { question: 'Is my data stored anywhere?', answer: 'No. All date calculations happen entirely in your browser using JavaScript. The dates you enter and the computed results are never transmitted to or stored on any server.' },
      { question: 'How is the years/months/days breakdown calculated?', answer: 'The tool uses calendar-aware arithmetic that respects actual month lengths. For example, the duration from January 31 to March 1 correctly accounts for February\'s length (28 or 29 days). This gives you a more meaningful breakdown than simply dividing total days by 30 or 365.' },
    ],
  },
  'background-remover': {
    guide: {
      title: 'What is the AI Background Remover?',
      overview: 'The KagazKit AI Background Remover strips the background from any photograph using a cutting-edge AI model that runs entirely inside your web browser. Unlike cloud-based services that upload your photos to remote servers, our tool downloads a compact AI segmentation model directly to your browser and processes images locally on your device. This means your personal photos, product images, and identity documents are never exposed to any third-party server — providing absolute privacy with professional-quality results.',
      steps: [
        { step: 'Upload your image', description: 'Click "Select Photo" or drag-and-drop an image file. Supports JPG, PNG, and WebP formats up to 10MB.' },
        { step: 'Wait for AI processing', description: 'On first use, the AI model (~40MB) downloads to your browser. Subsequent uses are faster as the model is cached. Processing takes a few seconds.' },
        { step: 'Review the result', description: 'Compare the original image side-by-side with the background-removed version on a transparency checkerboard pattern.' },
        { step: 'Download transparent PNG', description: 'Click "Download Transparent PNG" to save the result with a transparent background, perfect for design work.' },
      ],
      features: [
        '100% local AI processing — photos never leave your device',
        'Professional-quality edge detection and subject isolation',
        'Transparent PNG output for seamless design integration',
        'Side-by-side original vs result comparison',
        'Works offline after the AI model is cached',
        'No signup, watermarks, or usage limits',
      ],
      useCases: [
        'E-commerce sellers creating clean product photos with transparent backgrounds for online store listings.',
        'Content creators isolating subjects from photos for thumbnails, social media posts, and presentation slides.',
        'Professionals creating passport-style photos with plain white backgrounds from casual selfies.',
        'Designers extracting subjects from photographs for collages, mockups, and marketing materials.',
      ],
    },
    faqs: [
      { question: 'Are my photos uploaded to a server?', answer: 'No! This tool represents a breakthrough in web technology. We use an advanced AI segmentation model (@imgly/background-removal) that runs completely inside your web browser using WebAssembly and WebGL. Your photos are processed on your device\'s GPU/CPU and never leave your machine. This provides absolute privacy for sensitive images.' },
      { question: 'Why does it take a few seconds to load the first time?', answer: 'The AI model needs to be downloaded to your browser the very first time you use the tool (approximately 40MB). Once downloaded, the model is cached by your browser, and subsequent images process much faster — typically in 2-5 seconds depending on image size and your device\'s processing power.' },
      { question: 'What image format is the output saved in?', answer: 'The final image is saved as a high-quality PNG with a fully transparent background. PNG is the industry standard for transparent images and is compatible with all design software (Photoshop, Canva, Figma), website builders, and presentation tools.' },
      { question: 'Can I use this on my phone?', answer: 'Yes, but performance varies by device. Modern smartphones with decent GPUs handle the processing well, though it may take slightly longer than on a desktop computer. We enforce a 10MB file size limit to prevent mobile browser crashes.' },
      { question: 'Why are HEIC and TIFF formats not supported?', answer: 'HEIC (used by iPhones) and TIFF formats are not natively supported by the WebGL-based AI processing pipeline in most browsers. Please convert your HEIC photos to JPG before uploading — most phones can do this automatically in their camera settings, or you can use a free online converter.' },
    ],
  },
  'ai-receipt-scanner': {
    guide: {
      title: 'What is the AI Receipt Scanner?',
      overview: 'The KagazKit AI Receipt Scanner uses Google Gemini Vision AI to instantly extract structured financial data from photographs of receipts, bills, and invoices. Unlike traditional OCR tools that produce messy blocks of unformatted text, our tool leverages a multimodal large language model (LLM) that actually understands the layout and logic of financial documents. It intelligently identifies merchant names, individual line items with their prices, tax amounts, and totals — then organizes everything into a clean, structured table that you can export directly to CSV for use in Excel or accounting software.',
      steps: [
        { step: 'Upload a receipt image', description: 'Take a clear photo of your receipt or bill and upload it. Ensure the text is legible and the image is well-lit.' },
        { step: 'Wait for AI extraction', description: 'The image is securely sent to the Google Gemini API for intelligent data extraction. Processing takes 3-8 seconds.' },
        { step: 'Review extracted data', description: 'Check the structured table showing merchant name, line items, individual prices, tax breakdown, and total amount.' },
        { step: 'Download CSV', description: 'Click "Download CSV" to export the extracted data as a spreadsheet file compatible with Excel, Google Sheets, and accounting software.' },
      ],
      features: [
        'AI-powered extraction using Google Gemini Vision models',
        'Identifies merchant, items, prices, taxes, and totals',
        'Structured table output (not raw OCR text)',
        'One-click CSV export for Excel and accounting tools',
        'Images processed in-memory and immediately discarded',
        'Works with handwritten and printed receipts',
      ],
      useCases: [
        'Freelancers digitizing business expense receipts for quarterly tax filing and deduction claims.',
        'Corporate employees scanning restaurant bills and travel receipts for expense reimbursement submissions.',
        'Small business owners converting paper invoices into digital records for GST input credit tracking.',
        'Personal finance enthusiasts tracking daily spending by scanning grocery and shopping receipts.',
      ],
    },
    faqs: [
      { question: 'How does the AI Receipt Scanner work?', answer: 'Our tool uses Google Gemini Vision AI, a multimodal large language model that can "see" and understand images. Unlike traditional OCR which just extracts raw text, our AI understands the financial layout of receipts — it identifies which text is a merchant name, which numbers are prices, how items relate to their prices, and what the tax and total amounts are. This produces structured, accurate data.' },
      { question: 'Is my receipt data stored or saved?', answer: 'No. Your receipt image is securely transmitted to the Google Gemini API for processing, the extracted data is returned to your browser, and the image is immediately discarded. We do not store, save, log, or use your financial documents for any purpose including model training.' },
      { question: 'What image formats are supported?', answer: 'You can upload standard image formats including JPG, PNG, and WEBP. For the best extraction results, ensure the image is well-lit, in focus, and the text on the receipt is legible. Blurry or dark images may produce incomplete or inaccurate results.' },
      { question: 'Why did my receipt fail to scan or show incorrect data?', answer: 'Our AI is strictly programmed to extract structured financial data (Item Name, Price, Tax, and Total). Highly unusual receipt layouts, handwritten receipts with poor legibility, non-English text, or documents that are not receipts may produce errors. For best results, use standard retail, grocery, or restaurant itemized receipts with clear print.' },
      { question: 'Can I export the extracted data to Excel?', answer: 'Yes! Once the AI successfully extracts the line items and totals, a "Download CSV" button appears. This downloads a spreadsheet file that opens directly in Microsoft Excel, Google Sheets, Apple Numbers, or any spreadsheet application. The CSV includes columns for item name, quantity, price, and total.' },
    ],
  },
};
