import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer | KagazKit',
  description: 'Disclaimer for KagazKit web utilities.',
  alternates: {
    canonical: '/disclaimer',
  },
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 w-full prose prose-slate">
      <h1 className="text-3xl font-bold text-slate-900 mb-6">Disclaimer</h1>
      
      <h2 className="text-2xl font-semibold text-slate-900 mt-8 mb-4">General Information</h2>
      <p>
        The information and tools provided by KagazKit are for general informational purposes only. All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or calculation generated by our tools.
      </p>

      <h2 className="text-2xl font-semibold text-slate-900 mt-8 mb-4">Financial Calculators</h2>
      <p>
        The tax calculators, EPF estimators, and SIP calculators are provided for illustrative purposes only. They do not constitute financial or tax advice. Actual tax liabilities or investment returns will vary based on individual circumstances and market conditions. You should consult a qualified financial advisor or chartered accountant before making any financial decisions based on these tools.
      </p>

      <h2 className="text-2xl font-semibold text-slate-900 mt-8 mb-4">Photo Resizer</h2>
      <p>
        The Photo Resizer attempts to compress images strictly to the target KB requirements. However, individual government portals may have specific undocumented constraints. Always verify the final output file before submitting your application.
      </p>
    </div>
  );
}
